### ISSUE TITLE
Include Username of the deployment user & App Label

### ISSUE THREAD

**Issue by nhalstead** [yokawasa/kubectl-plugin-socks5-proxy#3]
## What

When running this by many people, what if this also included the user who created the deployment?

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: socks5
  labels:
    env: test
    app: socks5-proxy
    deployedBy: ${whoami or $USER}
spec:
  containers:
  - name: socks5
    image: serjs/go-socks5-proxy
    ports:
    - containerPort: 1080
  nodeSelector:
    "kubernetes.io/os": linux

```

So the new lines would be:

```
    app: socks5-proxy
    deployedBy: ${whoami or $USER}
```

---

## Why

This would help tag and manage deployed pods and allows for _tracking_ of who deployed the proxy.
